### ISSUE TITLE
sigs.pl not producing correct output on Windows (except UNIX ASCII files)

### ISSUE THREAD

**Issue by BarryGould** [clausing/scripts#2]
Hi,

On Win8.1, 64-bit, sigs.pl works fine when run against it's own .pl source file, but on binary files and on DOS text files it does not appear to produce correct output.

example, download
https://www.sdcard.org/downloads/formatter_4/eula_windows/SDFormatterv4.zip

>perl "c:\Program Files (x86)\Utilities\SYS\sigs.pl" SDFormatterv4.zip
SDFormatterv4.zip:
  MD5:  c36bed46bc0fee26c66ec5ef7c0d4e9d
  SHA1: 28452f2fa2a96b00ab53e110784aecf1bca84cee
  SHA256: ac7d09903f919d81e8f04ae8385d5fffb746dc74595ace21bcb0035bfd6f4af6
  SHA512: 3b5049d46ddf62b7 4f9bfaa3d4e32d9e 0a590864deffb87e 2434a1b73ffa7f3c
          5fbb1055cf047c0b af78cc976f127306 01ba62c1f3dbb11b 99a7e1ae1054ace5
  SHA512: O1BJ1G3fYrdPm/qj1OMtngpZCGTe/7h+JDShtz/6fzxfuxBVzwR8C694zJdvEnMGAbpiwf
PbsRuZp+GuEFSs5Q==
  SHA3-256: cc346c666940ff8c1b01aeb8d3834cff2081bbf55760c033a91ef2a7edd59332

However, other hashing programs ouput differently:
>sha1sum SDFormatterv4.zip
83e49cbe2dd1dac8f0b802dde0f4612d167383e7 *SDFormatterv4.zip

>sha256sum SDFormatterv4.zip
823eeb78b8574d505bae7c37c246fa6388f4f0698e703f08d711c14b91d4f08a *SDFormatterv4.zip

>md5sum SDFormatterv4.zip
73dfcbcd9f970bb4e57c7dce84463f38 *SDFormatterv4.zip

The same is true on DOS text files with CRLF. 
It only works correctly in Windows on UNIX ASCII files.

Also, ISTM the 2nd SHA512 output should say SHA512base64 or something to that effect to be clearer.

Thanks!

**Comment by BarryGould** [comment]
Using ActivePerl,
>perl -v

This is perl 5, version 18, subversion 1 (v5.18.1) built for MSWin32-x86-multi-t
hread-64int
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Binary build 1800 [297570] provided by ActiveState http://www.ActiveState.com
Built Sep 20 2013 11:40:34

**Comment by clausing** [comment]
Thanx for the report, I think I know how to fix this one.

**Comment by clausing** [comment]
hmm...  it gets it right on Linux, so let me install ActiveState Perl and try it on Windows

**Comment by BarryGould** [comment]
Hi, it looks like binmode is required:
http://perldoc.perl.org/functions/binmode.html

**Comment by clausing** [comment]
That was my guess, too. I just can't get a working ActivePerl or StrawberryPerl installed on the Windows box that I currently have access to (I'm on the road this week).  I'll check that in tomorrow and you can see if that fixes it, if so, I'll mark this closed.

**Comment by BarryGould** [comment]
Working now, thanks!
